"""PDF renderer for `business_report` artifacts — fpdf2, no new deps.

Core fonts are Latin-1, so all text goes through _clean() (₹→Rs, smart
punctuation → ASCII) before hitting the page. Layout: branded header band,
KPI tile row, then sections — table / bars / list / text.
"""
from __future__ import annotations

from fpdf import FPDF

INK = (26, 26, 36)
ACCENT = (52, 148, 244)
MUTE = (120, 126, 140)
LINE = (228, 230, 236)
ZEBRA = (247, 248, 251)

_REPLACE = {
    "₹": "Rs. ", "—": " - ", "–": "-", "'": "'", """: '"', """: '"',
    "…": "...", "•": "-", "→": "->", "~": "~",
}


def _clean(s) -> str:
    t = str(s if s is not None else "")
    for k, v in _REPLACE.items():
        t = t.replace(k, v)
    return t.encode("latin-1", "replace").decode("latin-1")


class _Doc(FPDF):
    def footer(self):
        self.set_y(-14)
        self.set_font("helvetica", size=8)
        self.set_text_color(*MUTE)
        self.cell(0, 8, _clean(f"Generated by Sahayak · {self.business} · page {self.page_no()}"),
                  align="C")


def render_report_pdf(title: str, data: dict, business: str = "") -> bytes:
    pdf = _Doc(orientation="P", unit="mm", format="A4")
    pdf.business = _clean(business or data.get("business") or "")
    pdf.set_auto_page_break(True, margin=18)
    pdf.set_margins(14, 14, 14)
    pdf.add_page()
    W = pdf.w - pdf.l_margin - pdf.r_margin

    # ── header band ──
    pdf.set_fill_color(*INK)
    pdf.rect(0, 0, pdf.w, 34, "F")
    pdf.set_y(8)
    pdf.set_font("helvetica", "B", 9)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 4, "S A H A Y A K", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "B", 17)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, _clean(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", size=9)
    pdf.set_text_color(190, 196, 210)
    sub = " · ".join(x for x in [_clean(data.get("business") or business),
                                 _clean(data.get("period")), _clean(data.get("subtitle"))] if x)
    pdf.multi_cell(0, 4.5, sub, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # ── KPI tiles ──
    kpis = data.get("kpis") or []
    if kpis:
        per_row = min(len(kpis), 5)
        kw = (W - (per_row - 1) * 3) / per_row
        x0, y0 = pdf.get_x(), pdf.get_y()
        for i, k in enumerate(kpis):
            x = x0 + (i % per_row) * (kw + 3)
            y = y0 + (i // per_row) * 26
            pdf.set_xy(x, y)
            pdf.set_fill_color(*ZEBRA)
            pdf.set_draw_color(*LINE)
            pdf.rect(x, y, kw, 23, "DF")
            pdf.set_xy(x + 2.5, y + 2.5)
            pdf.set_font("helvetica", size=7)
            pdf.set_text_color(*MUTE)
            pdf.cell(kw - 5, 3.5, _clean(k.get("label", "")).upper())
            pdf.set_xy(x + 2.5, y + 7.5)
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(*INK)
            pdf.cell(kw - 5, 6, _clean(k.get("value", "—")))
            pdf.set_xy(x + 2.5, y + 15)
            pdf.set_font("helvetica", size=7)
            pdf.set_text_color(*MUTE)
            pdf.cell(kw - 5, 3.5, _clean(k.get("sub", "")))
        pdf.set_y(y0 + ((len(kpis) - 1) // per_row + 1) * 26 + 4)

    # ── sections ──
    for sec in data.get("sections") or []:
        if pdf.get_y() > pdf.h - 45:
            pdf.add_page()
        pdf.ln(2)
        pdf.set_font("helvetica", "B", 11)
        pdf.set_text_color(*INK)
        pdf.cell(0, 6, _clean(sec.get("heading", "")), new_x="LMARGIN", new_y="NEXT")
        pdf.set_draw_color(*LINE)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.l_margin + W, pdf.get_y())
        pdf.ln(2.5)

        kind = sec.get("kind")
        if kind == "table":
            _table(pdf, W, sec.get("columns") or [], sec.get("rows") or [])
        elif kind == "bars":
            _bars(pdf, W, sec.get("items") or [])
        elif kind == "list":
            for it in sec.get("items") or []:
                pdf.set_font("helvetica", size=9)
                pdf.set_text_color(*INK)
                pdf.multi_cell(0, 4.5, _clean(f"  -  {it}"),
                               new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)
        else:  # text
            pdf.set_font("helvetica", size=9.5)
            pdf.set_text_color(60, 64, 76)
            pdf.multi_cell(0, 5, _clean(sec.get("text", "")),
                           new_x="LMARGIN", new_y="NEXT")
        if sec.get("note"):
            pdf.set_font("helvetica", "I", 8)
            pdf.set_text_color(*MUTE)
            pdf.multi_cell(0, 4, _clean(sec["note"]), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    return bytes(pdf.output())


def _table(pdf: FPDF, W: float, columns: list, rows: list):
    if not columns:
        return
    n = len(columns)
    # last numeric-ish column right-aligns narrower
    widths = [W / n] * n
    pdf.set_font("helvetica", "B", 8.5)
    pdf.set_fill_color(*INK)
    pdf.set_text_color(255, 255, 255)
    for j, c in enumerate(columns):
        pdf.cell(widths[j], 6.5, _clean(c), border=0, fill=True,
                 align="R" if j == n - 1 else "L")
    pdf.ln()
    pdf.set_font("helvetica", size=8.5)
    for i, row in enumerate(rows):
        if pdf.get_y() > pdf.h - 22:
            pdf.add_page()
        pdf.set_fill_color(*(ZEBRA if i % 2 else (255, 255, 255)))
        pdf.set_text_color(*INK)
        for j in range(n):
            v = row[j] if j < len(row) else ""
            pdf.cell(widths[j], 6, _clean(v), border="B", fill=True,
                     align="R" if j == n - 1 else "L")
        pdf.ln()
    pdf.ln(1)


def _bars(pdf: FPDF, W: float, items: list):
    if not items:
        return
    mx = max((float(i.get("value") or 0) for i in items), default=1) or 1
    label_w = W * 0.32
    bar_w = W * 0.48
    for it in items:
        if pdf.get_y() > pdf.h - 22:
            pdf.add_page()
        y = pdf.get_y()
        pdf.set_font("helvetica", size=8.5)
        pdf.set_text_color(*INK)
        pdf.cell(label_w, 5.5, _clean(str(it.get("label", ""))[:38]))
        frac = max(0.0, min(1.0, float(it.get("value") or 0) / mx))
        pdf.set_fill_color(*ACCENT)
        if frac > 0:
            pdf.rect(pdf.l_margin + label_w + 2, y + 1.2, bar_w * frac, 3.2, "F")
        pdf.set_xy(pdf.l_margin + label_w + 4 + bar_w, y)
        pdf.set_font("helvetica", "B", 8.5)
        pdf.cell(W - label_w - bar_w - 4, 5.5, _clean(it.get("display", "")), align="R")
        pdf.ln(7)
    pdf.ln(1)
